name: Continuous Integration

on:

  push:

    branches:

      - main



jobs:

  zip-files:

    runs-on: ubuntu-latest

    steps:

      - name: ZIP

        uses: vimtor/action-zip@v1

        with:

          files: src/

          dest: production/lambda_function.zip

      - name: Upload S3

        uses: shallwefootball/s3-upload-action@master

        id: S3

        with:

          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws_bucket: ${{ secrets.AWS_BUCKET }}

          source_dir: production